version: "2"

services:
  filebox-app:
    container_name: "${PROJECT_NAME}_app"
    restart: always
    volumes: 
      - ${APP_MAIN_FOLDER}:/usr/src/app
    build: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      - bubble
  filebox-mongo:
    container_name: "${PROJECT_NAME}_mongo"
    image: mongo
    volumes:
      - filebox_mongo:/data/db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - bubble

networks:
  bubble:
    external: true

volumes:
  filebox_mongo: